// gitprofile.config.ts

const CONFIG = {
  github: {
    username: 'Lcolantoni',
  },
  base: '/',
  projects: {
    github: {
      display: true,
      header: 'Github Projects',
      mode: 'automatic',
      automatic: {
        sortBy: 'stars',
        limit: 8,
        exclude: {
          forks: false,
          projects: [],
        },
      },
      manual: {
        projects: [],
      },
    },
  },
  seo: {
    title: 'Portfolio of Colantoni Lucas',
    description: '',
    imageURL: '',
  },
  social: {
    linkedin: 'lucas-colantoni-39b196153',
    researchGate: '',
    facebook: '',
    instagram: '',
    reddit: '',
    threads: '',
    youtube: '',
    udemy: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '',
    stackoverflow: '',
    skype: '',
    telegram: '',
    website: '',
    phone: '',
    email: 'lucascolantoni@hotmail.com',
  },
  resume: {
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  skills: [
    'Power Bi',
    'AWS',
    'Pandas',
    'Numpy',
    'Matplotlib',
    'MySQL',
    'Git',
    'Streamlit',
  ],
  experiences: [
    {
      company: 'Hoffmann GNC',
      position: 'Salesman - Customer Support',
      from: 'April 2019',
      to: 'March 2020',
      companyLink: 'https://example.com',
    },
    {
      company: 'Estudio Juridico Solari',
      position: 'Customer Support - Administrator',
      from: 'February 2021',
      to: 'Present',
      companyLink: 'https://example.com',
    },
  ],
  certifications: [
    {
      name: 'Cambridge First Certificate',
      body: '179 /190',
      year: 'November 2018',
      link: 'https://example.com',
    },
    {
      name: 'Efset English Certificate',
      body: 'C2 Proficient',
      year: 'June 2024',
      link: 'https://cert.efset.org/2xAfeg',
    },
    {
      name: 'Henry Data Science Bootcamp',
      body: 'Part-Time Data Science Carreer',
      year: 'June 2024',
      link: 'https://www.soyhenry.com/',
    },
  ],
  educations: [
    {
      institution: 'Soy Henry',
      degree: 'Data Scientist',
      from: '2023',
      to: '2024',
    },
  ],
  themeConfig: {
    defaultTheme: 'lofi',
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'procyon',
    ],
    customTheme: {
      primary: '#fc055b',
      secondary: '#219aaf',
      accent: '#e8d03a',
      neutral: '#2A2730',
      'base-100': '#E3E3ED',
      '--rounded-box': '3rem',
      '--rounded-btn': '3rem',
    },
  },
  footer: `Made with <a 
      class="text-primary" href="https://github.com/arifszn/gitprofile"
      target="_blank"
      rel="noreferrer"
    >GitProfile</a> and ❤️`,
  enablePWA: true,
};

export default CONFIG;
